import React, { useEffect, useState } from "react";
import AdminLayout from "../../components/AdminLayout";
import { apiGetUsers, apiCreateUser, apiDeleteUser } from "../../api";
import { Plus, Trash2, Loader2, Copy, Check } from "lucide-react";

export default function AdminUsers() {
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [form, setForm] = useState({ email: "", first_name: "", last_name: "", username: "", password: "", role: "student" });
  const [formError, setFormError] = useState("");
  const [saving, setSaving] = useState(false);
  const [credentials, setCredentials] = useState(null); // To show after user creation
  const [copiedField, setCopiedField] = useState(null); // Track which field was copied
  const [copyError, setCopyError] = useState("");

  const load = () => {
    setLoading(true);
    apiGetUsers()
      .then(users => setUsers(users.filter(u => !u.is_deleted)))
      .catch(console.error)
      .finally(() => setLoading(false));
  };

  useEffect(load, []);

  const handleCreate = async (e) => {
    e.preventDefault();
    setFormError("");
    setSaving(true);
    try {
      const response = await apiCreateUser(form);
      
      // Show credentials modal if they were autogenerated
      if (response.credentials) {
        setCredentials(response.credentials);
      } else {
        setShowModal(false);
      }
      
      setForm({ email: "", first_name: "", last_name: "", username: "", password: "", role: "student" });
      load();
    } catch (err) {
      setFormError(err.message);
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async (userId) => {
    if (!window.confirm("Are you sure you want to delete this user?")) return;
    await apiDeleteUser(userId).catch(alert);
    load();
  };

  const copyTextFallback = (text) => {
    const textArea = document.createElement("textarea");
    textArea.value = text;
    textArea.style.position = "fixed";
    textArea.style.left = "-9999px";
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();

    try {
      return document.execCommand("copy");
    } finally {
      document.body.removeChild(textArea);
    }
  };

  const copyToClipboard = async (text, field) => {
    setCopyError("");
    try {
      if (
        typeof navigator !== "undefined" &&
        navigator.clipboard &&
        typeof navigator.clipboard.writeText === "function" &&
        typeof window !== "undefined" &&
        window.isSecureContext
      ) {
        await navigator.clipboard.writeText(text);
      } else {
        const ok = copyTextFallback(text);
        if (!ok) throw new Error("Clipboard fallback failed");
      }
      setCopiedField(field);
      setTimeout(() => setCopiedField(null), 2000);
    } catch (err) {
      setCopyError("Could not copy automatically. Please select and copy manually.");
    }
  };

  return (
    <AdminLayout>
      <div className="p-8">
        <div className="flex items-center justify-between mb-6">
          <h1 className="text-2xl font-bold text-gray-900">User Management</h1>
          <button
            onClick={() => setShowModal(true)}
            className="flex items-center space-x-2 bg-red-600 text-white px-4 py-2.5 rounded-xl font-medium hover:bg-red-700 transition shadow-sm"
          >
            <Plus size={18} />
            <span>New User</span>
          </button>
        </div>

        <div className="bg-white rounded-2xl shadow-sm border border-gray-100">
          {loading ? (
            <div className="p-6 text-center text-gray-400">Loading...</div>
          ) : (
            <table className="w-full">
              <thead>
                <tr className="text-xs text-gray-500 uppercase tracking-wider border-b border-gray-100">
                  <th className="px-6 py-3 text-left">Name</th>
                  <th className="px-6 py-3 text-left">Username</th>
                  <th className="px-6 py-3 text-left">Email</th>
                  <th className="px-6 py-3 text-left">Role</th>
                  <th className="px-6 py-3 text-left">Registered At</th>
                  <th className="px-6 py-3 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {users.map((u) => (
                  <tr key={u.id} className="hover:bg-gray-50 transition">
                    <td className="px-6 py-3 text-sm font-medium text-gray-900">{u.first_name} {u.last_name}</td>
                    <td className="px-6 py-3 text-sm text-gray-600">@{u.username}</td>
                    <td className="px-6 py-3 text-sm text-gray-500">{u.email || "-"}</td>
                    <td className="px-6 py-3">
                      <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${u.role === "admin" ? "bg-red-100 text-red-700" : "bg-blue-100 text-blue-700"}`}>
                        {u.role === "admin" ? "Admin" : "Student"}
                      </span>
                    </td>
                    <td className="px-6 py-3 text-sm text-gray-400">{new Date(u.created_at).toLocaleDateString("en-US")}</td>
                    <td className="px-6 py-3 text-right">
                      <button onClick={() => handleDelete(u.id)} className="text-gray-300 hover:text-red-500 transition">
                        <Trash2 size={16} />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>

      {/* Create user modal */}
      {showModal && (
        <div className="fixed inset-0 bg-black/40 backdrop-blur-sm flex items-center justify-center z-50">
          <div className="bg-white rounded-2xl shadow-xl w-full max-w-md p-6 m-4">
            <h2 className="text-lg font-bold text-gray-900 mb-4">Create User</h2>
            {formError && (
              <div className="bg-red-50 text-red-700 text-sm p-3 rounded-xl mb-4">{formError}</div>
            )}
            <form onSubmit={handleCreate} className="space-y-3">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-medium text-gray-600 mb-1">Last Name</label>
                  <input value={form.last_name} onChange={e => setForm(f => ({...f, last_name: e.target.value}))} required placeholder="Smith" className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:ring-2 focus:ring-red-500 outline-none bg-gray-50 focus:bg-white" />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-600 mb-1">First Name</label>
                  <input value={form.first_name} onChange={e => setForm(f => ({...f, first_name: e.target.value}))} required placeholder="John" className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:ring-2 focus:ring-red-500 outline-none bg-gray-50 focus:bg-white" />
                </div>
              </div>
              <div>
                <label className="block text-xs font-medium text-gray-600 mb-1">Email (optional)</label>
                <input type="email" value={form.email} onChange={e => setForm(f => ({...f, email: e.target.value}))} placeholder="student@school.edu" className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:ring-2 focus:ring-red-500 outline-none bg-gray-50 focus:bg-white" />
              </div>
              <div>
                <label className="block text-xs font-medium text-gray-600 mb-1">Username (Leave empty to auto-generate)</label>
                <input value={form.username} onChange={e => setForm(f => ({...f, username: e.target.value}))} placeholder="Will be auto-generated if empty" className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:ring-2 focus:ring-red-500 outline-none bg-gray-50 focus:bg-white" />
              </div>
              <div>
                <label className="block text-xs font-medium text-gray-600 mb-1">Password (Leave empty to auto-generate)</label>
                <input type="password" value={form.password} onChange={e => setForm(f => ({...f, password: e.target.value}))} placeholder="Will be auto-generated if empty" className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:ring-2 focus:ring-red-500 outline-none bg-gray-50 focus:bg-white" />
              </div>
              <div>
                <label className="block text-xs font-medium text-gray-600 mb-1">Role</label>
                <select value={form.role} onChange={e => setForm(f => ({...f, role: e.target.value}))} className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:ring-2 focus:ring-red-500 outline-none bg-gray-50 focus:bg-white">
                  <option value="student">Student</option>
                  <option value="admin">Admin</option>
                </select>
              </div>
              <div className="flex space-x-3 pt-2">
                <button type="button" onClick={() => setShowModal(false)} className="flex-1 border border-gray-200 rounded-xl py-2.5 text-sm font-medium text-gray-600 hover:bg-gray-50 transition">Cancel</button>
                <button type="submit" disabled={saving} className="flex-1 flex items-center justify-center space-x-2 bg-red-600 text-white rounded-xl py-2.5 text-sm font-medium hover:bg-red-700 transition disabled:opacity-70">
                  {saving && <Loader2 size={14} className="animate-spin" />}
                  <span>Create</span>
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Credentials display modal */}
      {credentials && (
        <div className="fixed inset-0 bg-black/40 backdrop-blur-sm flex items-center justify-center z-50">
          <div className="bg-white rounded-2xl shadow-xl w-full max-w-md p-6 m-4">
            <h2 className="text-lg font-bold text-gray-900 mb-2">Student Credentials Created</h2>
            <p className="text-sm text-gray-500 mb-4">Copy and share these credentials with the student:</p>
            
            <div className="space-y-3 bg-gray-50 p-4 rounded-xl mb-4">
              <div>
                <label className="block text-xs font-medium text-gray-600 mb-1.5">Username</label>
                <div className="flex items-center space-x-2">
                  <code className="flex-1 bg-white border border-gray-200 px-3 py-2.5 rounded-lg text-sm font-mono text-gray-900">{credentials.username}</code>
                  <button
                    onClick={() => copyToClipboard(credentials.username, 'username')}
                    className="p-2 hover:bg-gray-200 rounded-lg transition"
                  >
                    {copiedField === 'username' ? (
                      <Check size={16} className="text-green-600" />
                    ) : (
                      <Copy size={16} className="text-gray-600" />
                    )}
                  </button>
                </div>
              </div>
              <div>
                <label className="block text-xs font-medium text-gray-600 mb-1.5">Password</label>
                <div className="flex items-center space-x-2">
                  <code className="flex-1 bg-white border border-gray-200 px-3 py-2.5 rounded-lg text-sm font-mono text-gray-900">{credentials.password}</code>
                  <button
                    onClick={() => copyToClipboard(credentials.password, 'password')}
                    className="p-2 hover:bg-gray-200 rounded-lg transition"
                  >
                    {copiedField === 'password' ? (
                      <Check size={16} className="text-green-600" />
                    ) : (
                      <Copy size={16} className="text-gray-600" />
                    )}
                  </button>
                </div>
              </div>
            </div>

            <div className="bg-blue-50 border border-blue-200 rounded-xl p-3 mb-4">
              <p className="text-xs text-blue-700">💡 <span className="font-medium">Tip:</span> Click the copy icon to copy each field. Send both to the student via secure channel.</p>
            </div>

            {copyError && (
              <div className="bg-amber-50 border border-amber-200 rounded-xl p-3 mb-4 text-xs text-amber-700">
                {copyError}
              </div>
            )}

            <div className="flex space-x-3">
              <button
                type="button"
                onClick={() => {
                  setCredentials(null);
                  setShowModal(false);
                }}
                className="flex-1 border border-gray-200 rounded-xl py-2.5 text-sm font-medium text-gray-600 hover:bg-gray-50 transition"
              >
                Close
              </button>
              <button
                type="button"
                onClick={() => {
                  copyToClipboard(`Username: ${credentials.username}\nPassword: ${credentials.password}`, 'both');
                }}
                className="flex-1 flex items-center justify-center space-x-2 bg-red-600 text-white rounded-xl py-2.5 text-sm font-medium hover:bg-red-700 transition"
              >
                {copiedField === 'both' ? (
                  <>
                    <Check size={14} />
                    <span>Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy size={14} />
                    <span>Copy Both</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      )}
    </AdminLayout>
  );
}
